const assert=require('node:assert/strict');
const C=require('./can.js');
assert.equal(C.hex(0x1fffffff),'0x1FFFFFFF');
assert.equal(C.capture('throttle',10),'EXPERIMENT THROTTLE 10');
assert.equal(C.capture('',10,true),'BASELINE 10');
for(const seconds of [0,-1,3601,1.2,NaN,Infinity,'1x'])assert.throws(()=>C.capture('ACTION',seconds));
for(const label of ['', 'has space','a'.repeat(24),'<script>','label\nSTOP'])assert.throws(()=>C.capture(label,10));
assert.throws(()=>C.packet({mode:'NORMAL',ids:[],candidates:[]}));
assert.throws(()=>C.packet({mode:'LISTEN_ONLY',ids:new Array(129),candidates:[]}));
assert.throws(()=>C.packet({mode:'LISTEN_ONLY',ids:[],candidates:new Array(13)}));
assert.equal(C.packet({mode:'LISTEN_ONLY',ids:[],candidates:[]}).ids.length,0);
console.log('PASS: CAN mode, bounded payloads, experiment durations/labels, hexadecimal identifiers');
